name: Python application Scheduler

on:
  [workflow_dispatch]
#  schedule:
#    - cron: "* * * * *"
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run command line and update csv to github
      run: |
        python main.py ${{ secrets.API_KEY }} .
        git config --global user.email "saadkhandev@gmail.com"
        git config --global user.name "Saad Khan"
        git checkout master
        git add .
        git commit --amend -m "update csv"
        git push --force
